@host= http://localhost:8080/api/v1/user
@token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZWY2NmE4LTE4N2QtNDU0Zi1iMDFhLTlhMmNhZGQzYzgxZSIsImVtYWlsIjoiZWplbXBsb0BnbWFpbC5jb20iLCJpYXQiOjE2NjA1MTEwMTEsImV4cCI6MTY2MDY4MzgxMX0.4htc0E8lhHEtP22Z5KW2d3593IU88908qaG_7YW1Eyo

@name="user2"
@password="123"
@email="ejemplo@gmail.com"
### crear usuario
POST  {{host}}/register
Content-Type: application/json

{
"name": {{name}},
"email": {{email}} ,
"password": {{password}},
"passwordConfirm": {{password}}
}
### login sin token (email)
POST {{host}}/login
Content-Type: application/json

{
"email": {{email}},
"password": {{password}}
}
### login con token

POST {{host}}/login
authorization: {{token1}}

