@host= http://localhost:8080/api/v1/meme
@token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI5ZTZmZTBjLWI1NTItNGYwYy04ZTlhLWM3Yjk0NzMyMWE4NiIsImVtYWlsIjoiZWplbXBsb0BnbWFpbC5jb20iLCJpYXQiOjE2NTk4MTg2MjcsImV4cCI6MTY1OTk5MTQyN30.O3CW4QEFWGyQFdurfc3pzPxxb0lCmjnb_AT4NHJu9c4

@name="nameImg"
@access=true

@idMeme=b3f723f5-02d2-4217-8749-5de921e4e5ad

### Create Meme
POST  {{host}}/create
Content-Type: application/json
authorization: {{token1}}

{
"name": {{name}},
"access": {{access}}
### file, no se como colocar un archivo, echo en PostMan
}

### Update Meme
POST  {{host}}/update/{{idMeme}}
Content-Type: application/json
authorization: {{token1}}

{
"name": {{name}}
}