@host= http://localhost:8080/api/v1/user
@token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUzNTEwNTkzLCJleHAiOjE2NTM2ODMzOTN9.sNpc94bOOQ8Z6D3tKGOn8XgBTRMhm60fP6wI5sZ-F1o

@name="user2"
@password="123"
@email="ejemplo@ejemplo.com"
### crear usuario
POST  {{host}}/register
Content-Type: application/json

{
"name": {{name}},
"email": {{email}} ,
"password": {{password}},
"passwordConfirm": {{password}}
}
### login sin token (userName)
POST {{host}}/login
Content-Type: application/json

{
"name": {{name}},
"password": {{password}}
}
### login sin token (email)
POST {{host}}/login
Content-Type: application/json

{
"email": {{email}},
"password": {{password}}
}
### login con token

POST {{host}}/login
authorization: {{token1}}

